function [images] = load_images()
images_dir = '../images';
image_names = {
    'A.jpg', ...
    'B.jpg', ...
    'C.jpg', ...
    'D.jpg', ...
    'E.jpg', ...
    'H.jpg', ...
    'I.jpg', ...
    'K.jpg', ...
    'L.jpg', ...
    'M.jpg', ...
    'N.jpg', ...
    'P.jpg', ...
    'S.jpg', ...
    'U.jpg', ...
    'W.jpg', ...
    'X.jpg', ...
    'O.jpg', ...
    '4.jpg', ...
    '5.jpg', ...
    '1.jpg'
    };
images = {};
for name = image_names
    image = imread(fullfile(images_dir, name{1}));
    image = rgb2gray(image);
    images{end + 1} = image;
end
end
