function [model, model_connections] = ...
    simulate_model(model, params, is_pre_training, model_connections)

if is_pre_training
    n = params.n_pre_training;
else
    n = params.n_test;
end

for i = 1 : n
    if rem(i, 1000) == 0
        disp([i, n]);
    end
    
    [model.V_line_E(:,1), ...
        model.V_line_I(:,1), ...
        model.U_line_E(:,1), ...
        model.U_line_I(:,1), ...
        model.G(:,1), ...
        model.Isyn_line_EE, ...
        model.Isyn_line_EI, ...
        model.Isyn_line_IE, ...
        model_connections.W_EE, ...
        model_connections.W_EI, ...
        model.is_active, ...
        model.Mask_line] = ...
        step_neurons(model.V_line_E(:,1), ...
                     model.V_line_I(:,1), ...
                     model.U_line_E(:,1), ...
                     model.U_line_I(:,1), ...
                     model.G(:,1), ...
                     model.T_Iapp_met(i), ...
                     model.T_Iapp,...
                     model.Iapp, ...
                     model.Isyn_line_EE, ...
                     model.Isyn_line_EI, ...
                     model.Isyn_line_IE, ...
                     model_connections.Post_EE, ...
                     model_connections.Pre_EE, ...
                     model_connections.Post_EI, ...
                     model_connections.Pre_EI, ...
                     model_connections.Post_IE, ...
                     model_connections.Pre_IE, ...
                     model_connections.W_EE, ...
                     model_connections.W_EI, ...
                     model.is_active, ...
                     model.Iastro_neuron_line,...
                     is_pre_training, i);
    
    if ~is_pre_training
        model.V_line_E_full(:,i) = model.V_line_E(:,1);
        [model.neuron_astrozone_activity, ...
         model.neuron_astrozone_spikes(:,:,i)] = ...
            get_neuron_astrozone_activity(model.G(:,1),  model.Mask_line);
        
        [model.Ca(:,:,1), ...
         model.H(:,:,1), ...
         model.IP3(:,:,1), ...
         model.Iastro_neuron, ...
         model.Ineuro] = ...
            step_astrocytes(model.neuron_astrozone_activity(:,:,1), ...
                            model.neuron_astrozone_spikes, ...
                            model.Ineuro, i, ...
                            model.Ca(:,:,1), ...
                            model.H(:,:,1), ...
                            model.IP3(:,:,1), ...
                            model.Iastro_neuron);
        
        [model.Iastro_neuron_line(:,1)] = ...
            expand_astrocytes(model.Iastro_neuron(:,:,i));
    end
end
end